#ifndef MYOS_KERNEL_ARCH_X64_CONSTANT_H_
#define MYOS_KERNEL_ARCH_X64_CONSTANT_H_

// Model-Specific Registers
#define MSR_APIC_BASE 0x0000001B

// CPUID flags
#define CPUID_FEATURE_EDX_APIC (1u<<9)

#endif // MYOS_KERNEL_ARCH_X64_CONSTANT_H_
