#ifndef MYOS_KERNEL_BOOTINFO_H_
#define MYOS_KERNEL_BOOTINFO_H_

#define BOOTINFO_START_ADDR         0x8000
#define BOOTINFO_DRIVE_NO_ADDR      (BOOTINFO_START_ADDR+0x00)
#define BOOTINFO_SECTORS_ADDR       (BOOTINFO_START_ADDR+0x02)
#define BOOTINFO_HEADS_ADDR         (BOOTINFO_START_ADDR+0x04)
#define BOOTINFO_TRACKS_ADDR        (BOOTINFO_START_ADDR+0x06)
#define BOOTINFO_SMAP_NENTRIES_ADDR (BOOTINFO_START_ADDR+0x10)
#define BOOTINFO_SMAP_START_ADDR    (BOOTINFO_START_ADDR+0x20)
#define BOOTINFO_SMAP_ENTRY_SIZE    24

#endif  // MYOS_KERNEL_BOOTINFO_H_
