#ifndef MYOS_KERNEL_CONFIG_H_
#define MYOS_KERNEL_CONFIG_H_

#ifndef CONFIG_KERNEL_PBASE
#define CONFIG_KERNEL_PBASE  0x10000
#endif

#ifndef CONFIG_KERNEL_VSPACE_OFFSET
#define CONFIG_KERNEL_VSPACE_OFFSET 0xffff880000000000
#endif

#ifndef CONFIG_KERNEL_VBASE
#define CONFIG_KERNEL_VBASE (CONFIG_KERNEL_VSPACE_OFFSET + CONFIG_KERNEL_PBASE)
#endif

#ifndef CONFIG_STRAIGHT_MAP_REGION_SIZE_IN_GB
#define CONFIG_STRAIGHT_MAP_REGION_SIZE_IN_GB 8
#endif

#ifndef CONFIG_PAGE_SIZE
#define CONFIG_PAGE_SIZE    4096
#endif

#endif // MYOS_KERNEL_CONFIG_H_
